site_name: Material for MkDocs Portfolio Template
repo_name: MrChike/mkdocs-portfolio

nav:
  - Home: index.md
  - Projects: projects.md
  - Contributions: contributions.md
  - Certifications: certifications.md
  - Articles: articles.md

theme:
  name: material
  favicon: https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/materialformkdocs.svg
  custom_dir: docs/overrides
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

